title: Web Reversing Guide
description: A comprehensive guide to web application reverse engineering
baseurl: "/web-reversing/"

# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme