title: Web Reversing Guide
description: A comprehensive guide to web application reverse engineering
baseurl: ""
url: ""

# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme

navigation:
  - title: Home
    url: /web-reversing/
  - title: Getting Started
    url: /web-reversing/chapters/0_getting_started
  - title: Understanding Packers
    url: /web-reversing/chapters/1_understanding_packers
  - title: Intro to Transformation & Obfuscation
    url: /web-reversing/chapters/2_intro_to_transformation_obfuscation
  - title: Defeating Anti-Tampering
    url: /web-reversing/chapters/3_defeating_anti_tampering